services:
  # product_svc:
  #   image: ducnta99/letobserv-products
  #   container_name: products_service_app
  #   env_file:
  #     - product.env 
  #   environment:
  #     DB_HOST: products_db
  #     DB_PORT: 5432
  #     SERVICE_NAME: product_service
  #     SERVICE_PORT: 9420
  #   ports:
  #     - "127.0.0.1:${DB_PORT}:9420"
  #   networks:
  #     - localnet
  #   depends_on:
  #     products_db:
  #       condition: service_healthy
  #   restart: unless-stopped

  clickstack:
    image: clickhouse/clickstack-all-in-one:2.11.0
    container_name: clickstack
    ports:
      - "8123:8123"   # ClickHouse HTTP
      - "9000:9000"   # ClickHouse Native
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - ./.docker/clickstack/data:/var/lib/clickhouse
      - ./.docker/clickstack/logs:/var/log/clickhouse
    restart: unless-stopped

  postgres:
    image: postgres:17.5-alpine
    container_name: postgres_db
    env_file:
      - .env 
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "${DB_PORT}:5432"
    networks:
      - localnet
    volumes:
      - ./.docker/pg-data:/data/postgres
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
      start_interval: 60s
    restart: unless-stopped

  migrate_inventory_db:
    image: migrate/migrate
    container_name: migrate_inventory_db
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [/wait-and-migrate.sh]
    restart: "no"
    volumes:
      - ./scripts/migrate_inventory_db.sh:/wait-and-migrate.sh
      - ./migrations/inventory/schemas:/migrations
    networks:
      - localnet
  
  migrate_order_db:
    image: migrate/migrate
    container_name: migrate_order_db
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [/wait-and-migrate.sh]
    restart: "no"
    volumes:
      - ./scripts/migrate_orders_db.sh:/wait-and-migrate.sh
      - ./migrations/orders/schemas:/migrations
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
