services:
  # product_svc:
  #   image: ducnta99/letobserv-products
  #   container_name: products_service_app
  #   env_file:
  #     - product.env 
  #   environment:
  #     DB_HOST: products_db
  #     DB_PORT: 5432
  #     SERVICE_NAME: product_service
  #     SERVICE_PORT: 9420
  #   ports:
  #     - "127.0.0.1:${DB_PORT}:9420"
  #   networks:
  #     - localnet
  #   depends_on:
  #     products_db:
  #       condition: service_healthy
  #   restart: unless-stopped

  products_db:
    image: postgres:17.5-alpine
    container_name: pg_products_service
    env_file:
      - product.env 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - localnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    container_name: ${SERVICE_ENV}_migrate_${PRODUCT_SERVICE_NAME}
    depends_on:
      products_db:
        condition: service_healthy
    entrypoint:
      [
        "sh",
        "-c",
        "migrate -path=/migrations -database=postgres://${DB_PRODUCT_USERNAME}:${DB_PRODUCT_PASSWORD}@products_db:5432/${DB_PRODUCT_DATABASE}?sslmode=disable up",
      ]
    restart: "no"
    volumes:
      - ./migrations:/migrations
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
