// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package order

import (
	"context"

	"github.com/ductran999/letobserv/services/placement/internal/modules/order/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryRestful creates a new instance of MockInventoryRestful. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryRestful(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryRestful {
	mock := &MockInventoryRestful{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryRestful is an autogenerated mock type for the InventoryRestful type
type MockInventoryRestful struct {
	mock.Mock
}

type MockInventoryRestful_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryRestful) EXPECT() *MockInventoryRestful_Expecter {
	return &MockInventoryRestful_Expecter{mock: &_m.Mock}
}

// GetProduct provides a mock function for the type MockInventoryRestful
func (_mock *MockInventoryRestful) GetProduct(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryRestful_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockInventoryRestful_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockInventoryRestful_Expecter) GetProduct(ctx interface{}, id interface{}) *MockInventoryRestful_GetProduct_Call {
	return &MockInventoryRestful_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, id)}
}

func (_c *MockInventoryRestful_GetProduct_Call) Run(run func(ctx context.Context, id string)) *MockInventoryRestful_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryRestful_GetProduct_Call) Return(err error) *MockInventoryRestful_GetProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryRestful_GetProduct_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockInventoryRestful_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type MockInventoryRestful
func (_mock *MockInventoryRestful) Reserve(ctx context.Context, req order.InventoryReserveRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.InventoryReserveRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryRestful_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockInventoryRestful_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - req order.InventoryReserveRequest
func (_e *MockInventoryRestful_Expecter) Reserve(ctx interface{}, req interface{}) *MockInventoryRestful_Reserve_Call {
	return &MockInventoryRestful_Reserve_Call{Call: _e.mock.On("Reserve", ctx, req)}
}

func (_c *MockInventoryRestful_Reserve_Call) Run(run func(ctx context.Context, req order.InventoryReserveRequest)) *MockInventoryRestful_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.InventoryReserveRequest
		if args[1] != nil {
			arg1 = args[1].(order.InventoryReserveRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryRestful_Reserve_Call) Return(err error) *MockInventoryRestful_Reserve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryRestful_Reserve_Call) RunAndReturn(run func(ctx context.Context, req order.InventoryReserveRequest) error) *MockInventoryRestful_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Create(ctx context.Context, order1 *order.Order) error {
	ret := _mock.Called(ctx, order1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *order.Order) error); ok {
		r0 = returnFunc(ctx, order1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order1 *order.Order
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, order1 interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order1)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, order1 *order.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *order.Order
		if args[1] != nil {
			arg1 = args[1].(*order.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(err error) *MockOrderRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, order1 *order.Order) error) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetByID(ctx context.Context, id string) (*order.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*order.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *order.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockOrderRepository_GetByID_Call {
	return &MockOrderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrderRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockOrderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) Return(order1 *order.Order, err error) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*order.Order, error)) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetOrder(ctx context.Context, id string) (*order.PlacedOrder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *order.PlacedOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*order.PlacedOrder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *order.PlacedOrder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.PlacedOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockUseCase_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUseCase_Expecter) GetOrder(ctx interface{}, id interface{}) *MockUseCase_GetOrder_Call {
	return &MockUseCase_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockUseCase_GetOrder_Call) Run(run func(ctx context.Context, id string)) *MockUseCase_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetOrder_Call) Return(placedOrder *order.PlacedOrder, err error) *MockUseCase_GetOrder_Call {
	_c.Call.Return(placedOrder, err)
	return _c
}

func (_c *MockUseCase_GetOrder_Call) RunAndReturn(run func(ctx context.Context, id string) (*order.PlacedOrder, error)) *MockUseCase_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PlacePOrder provides a mock function for the type MockUseCase
func (_mock *MockUseCase) PlacePOrder(ctx context.Context, input order.PlaceOrderRequest) (*order.PlacedOrderOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PlacePOrder")
	}

	var r0 *order.PlacedOrderOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.PlaceOrderRequest) (*order.PlacedOrderOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.PlaceOrderRequest) *order.PlacedOrderOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.PlacedOrderOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.PlaceOrderRequest) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_PlacePOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlacePOrder'
type MockUseCase_PlacePOrder_Call struct {
	*mock.Call
}

// PlacePOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - input order.PlaceOrderRequest
func (_e *MockUseCase_Expecter) PlacePOrder(ctx interface{}, input interface{}) *MockUseCase_PlacePOrder_Call {
	return &MockUseCase_PlacePOrder_Call{Call: _e.mock.On("PlacePOrder", ctx, input)}
}

func (_c *MockUseCase_PlacePOrder_Call) Run(run func(ctx context.Context, input order.PlaceOrderRequest)) *MockUseCase_PlacePOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.PlaceOrderRequest
		if args[1] != nil {
			arg1 = args[1].(order.PlaceOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_PlacePOrder_Call) Return(placedOrderOutput *order.PlacedOrderOutput, err error) *MockUseCase_PlacePOrder_Call {
	_c.Call.Return(placedOrderOutput, err)
	return _c
}

func (_c *MockUseCase_PlacePOrder_Call) RunAndReturn(run func(ctx context.Context, input order.PlaceOrderRequest) (*order.PlacedOrderOutput, error)) *MockUseCase_PlacePOrder_Call {
	_c.Call.Return(run)
	return _c
}
