// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ductran999/letobserv/services/inventory/internal/modules/inventory/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryRepo creates a new instance of MockInventoryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryRepo {
	mock := &MockInventoryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryRepo is an autogenerated mock type for the InventoryRepo type
type MockInventoryRepo struct {
	mock.Mock
}

type MockInventoryRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryRepo) EXPECT() *MockInventoryRepo_Expecter {
	return &MockInventoryRepo_Expecter{mock: &_m.Mock}
}

// CreateReservation provides a mock function for the type MockInventoryRepo
func (_mock *MockInventoryRepo) CreateReservation(ctx context.Context, reservation inventory.InventoryReservation) error {
	ret := _mock.Called(ctx, reservation)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inventory.InventoryReservation) error); ok {
		r0 = returnFunc(ctx, reservation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryRepo_CreateReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReservation'
type MockInventoryRepo_CreateReservation_Call struct {
	*mock.Call
}

// CreateReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - reservation inventory.InventoryReservation
func (_e *MockInventoryRepo_Expecter) CreateReservation(ctx interface{}, reservation interface{}) *MockInventoryRepo_CreateReservation_Call {
	return &MockInventoryRepo_CreateReservation_Call{Call: _e.mock.On("CreateReservation", ctx, reservation)}
}

func (_c *MockInventoryRepo_CreateReservation_Call) Run(run func(ctx context.Context, reservation inventory.InventoryReservation)) *MockInventoryRepo_CreateReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inventory.InventoryReservation
		if args[1] != nil {
			arg1 = args[1].(inventory.InventoryReservation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryRepo_CreateReservation_Call) Return(err error) *MockInventoryRepo_CreateReservation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryRepo_CreateReservation_Call) RunAndReturn(run func(ctx context.Context, reservation inventory.InventoryReservation) error) *MockInventoryRepo_CreateReservation_Call {
	_c.Call.Return(run)
	return _c
}

// GetStock provides a mock function for the type MockInventoryRepo
func (_mock *MockInventoryRepo) GetStock(ctx context.Context, productID string) (*inventory.InventoryStock, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 *inventory.InventoryStock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*inventory.InventoryStock, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *inventory.InventoryStock); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.InventoryStock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryRepo_GetStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStock'
type MockInventoryRepo_GetStock_Call struct {
	*mock.Call
}

// GetStock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockInventoryRepo_Expecter) GetStock(ctx interface{}, productID interface{}) *MockInventoryRepo_GetStock_Call {
	return &MockInventoryRepo_GetStock_Call{Call: _e.mock.On("GetStock", ctx, productID)}
}

func (_c *MockInventoryRepo_GetStock_Call) Run(run func(ctx context.Context, productID string)) *MockInventoryRepo_GetStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryRepo_GetStock_Call) Return(inventoryStock *inventory.InventoryStock, err error) *MockInventoryRepo_GetStock_Call {
	_c.Call.Return(inventoryStock, err)
	return _c
}

func (_c *MockInventoryRepo_GetStock_Call) RunAndReturn(run func(ctx context.Context, productID string) (*inventory.InventoryStock, error)) *MockInventoryRepo_GetStock_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseReserved provides a mock function for the type MockInventoryRepo
func (_mock *MockInventoryRepo) IncreaseReserved(ctx context.Context, productID string, quantity int) error {
	ret := _mock.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseReserved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryRepo_IncreaseReserved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseReserved'
type MockInventoryRepo_IncreaseReserved_Call struct {
	*mock.Call
}

// IncreaseReserved is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - quantity int
func (_e *MockInventoryRepo_Expecter) IncreaseReserved(ctx interface{}, productID interface{}, quantity interface{}) *MockInventoryRepo_IncreaseReserved_Call {
	return &MockInventoryRepo_IncreaseReserved_Call{Call: _e.mock.On("IncreaseReserved", ctx, productID, quantity)}
}

func (_c *MockInventoryRepo_IncreaseReserved_Call) Run(run func(ctx context.Context, productID string, quantity int)) *MockInventoryRepo_IncreaseReserved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventoryRepo_IncreaseReserved_Call) Return(err error) *MockInventoryRepo_IncreaseReserved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryRepo_IncreaseReserved_Call) RunAndReturn(run func(ctx context.Context, productID string, quantity int) error) *MockInventoryRepo_IncreaseReserved_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// InventoryReserve provides a mock function for the type MockUsecase
func (_mock *MockUsecase) InventoryReserve(ctx context.Context, req inventory.InventoryReserveInput) (*inventory.InventoryReservationView, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InventoryReserve")
	}

	var r0 *inventory.InventoryReservationView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inventory.InventoryReserveInput) (*inventory.InventoryReservationView, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inventory.InventoryReserveInput) *inventory.InventoryReservationView); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory.InventoryReservationView)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inventory.InventoryReserveInput) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_InventoryReserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InventoryReserve'
type MockUsecase_InventoryReserve_Call struct {
	*mock.Call
}

// InventoryReserve is a helper method to define mock.On call
//   - ctx context.Context
//   - req inventory.InventoryReserveInput
func (_e *MockUsecase_Expecter) InventoryReserve(ctx interface{}, req interface{}) *MockUsecase_InventoryReserve_Call {
	return &MockUsecase_InventoryReserve_Call{Call: _e.mock.On("InventoryReserve", ctx, req)}
}

func (_c *MockUsecase_InventoryReserve_Call) Run(run func(ctx context.Context, req inventory.InventoryReserveInput)) *MockUsecase_InventoryReserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inventory.InventoryReserveInput
		if args[1] != nil {
			arg1 = args[1].(inventory.InventoryReserveInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_InventoryReserve_Call) Return(inventoryReservationView *inventory.InventoryReservationView, err error) *MockUsecase_InventoryReserve_Call {
	_c.Call.Return(inventoryReservationView, err)
	return _c
}

func (_c *MockUsecase_InventoryReserve_Call) RunAndReturn(run func(ctx context.Context, req inventory.InventoryReserveInput) (*inventory.InventoryReservationView, error)) *MockUsecase_InventoryReserve_Call {
	_c.Call.Return(run)
	return _c
}
